cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'roundup'
brew 'spark'
brew 'unrar'
brew 'yarn'

cask '1password'
cask 'alfred'
cask 'atom'
cask 'balsamiq-mockups'
cask 'charles'
cask 'dropbox'
cask 'firefox'
cask 'gitter'
cask 'google-chrome'
cask 'google-drive'
cask 'kaleidoscope'
cask 'opera'
cask 'private-internet-access'
cask 'sketch'
cask 'slack'
cask 'sublime-text'
cask 'synergy'
cask 'tower'
cask 'vmware-fusion'
# cask 'transmit'
cask 'zeplin'